apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-image-updater-git-creds
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: argocd-image-updater-git-creds
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: eks-platform/dev/argocd/github-infra-repo-token
        property: username
    - secretKey: password
      remoteRef:
        key: eks-platform/dev/argocd/github-infra-repo-token
        property: password
