apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backend-db-secret
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: backend-db-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: eks-platform/dev/backend/db-damir
        property: DB_PASSWORD
